# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


region1 = Region.create(name: "Africa", url_name: "africa")
region2 = Region.create(name: "Asia", url_name: "asia")
region3 = Region.create(name: "Caribbean", url_name: "caribbean")
region4 = Region.create(name: "Central America and Mexico", url_name: "central_america_mexico")
region5 = Region.create(name: "Eastern Europe and Central Asia", url_name: "eastern_europe_central_ssia")
region6 = Region.create(name: "North Africa and the Middle East", url_name: "north_africa_middle_east")
region7 = Region.create(name: "Pacific Islands", url_name: "pacific_islands")
region8 = Region.create(name: "South America", url_name: "south_america")


Country.create(name: "Benin", url_name: "benin", region_id: region1.id)
Country.create(name: "Botswana", url_name: "botswana", region_id: region1.id)
Country.create(name: "Burkina Faso", url_name: "burkina_faso", region_id: region1.id)
Country.create(name: "Cameroon", url_name: "cameroon", region_id: region1.id)
Country.create(name: "Comoros", url_name: "comoros", region_id: region1.id)
Country.create(name: "Ethiopia", url_name: "ethiopia", region_id: region1.id)
Country.create(name: "Ghana", url_name: "ghana", region_id: region1.id)
Country.create(name: "Guinea", url_name: "guinea", region_id: region1.id)
Country.create(name: "Kenya", url_name: "kenya", region_id: region1.id)
Country.create(name: "Lesotho", url_name: "lesotho", region_id: region1.id)
Country.create(name: "Liberia", url_name: "liberia", region_id: region1.id)
Country.create(name: "Madagascar", url_name: "madagascar", region_id: region1.id)
Country.create(name: "Malawi", url_name: "malawi", region_id: region1.id)
Country.create(name: "Mali", url_name: "mali", region_id: region1.id)
Country.create(name: "Mozambique", url_name: "mozambique", region_id: region1.id)
Country.create(name: "Namibia", url_name: "namibia", region_id: region1.id)
Country.create(name: "Niger", url_name: "niger", region_id: region1.id)
Country.create(name: "Rwanda", url_name: "rwanda", region_id: region1.id)
Country.create(name: "Senegal", url_name: "senegal", region_id: region1.id)
Country.create(name: "Sierra Leone", url_name: "sierra_leone", region_id: region1.id)
Country.create(name: "South Africa", url_name: "south_africa", region_id: region1.id)
Country.create(name: "Swaziland", url_name: "swaziland", region_id: region1.id)
Country.create(name: "Tanzania", url_name: "tanzania", region_id: region1.id)
Country.create(name: "The Gambia", url_name: "the_gambia", region_id: region1.id)
Country.create(name: "Togo", url_name: "togo", region_id: region1.id)
Country.create(name: "Uganda", url_name: "uganda", region_id: region1.id)
Country.create(name: "Zambia", url_name: "zambia", region_id: region1.id)

Country.create(name: "Cambodia", url_name: "cambodia", region_id: region2.id)
Country.create(name: "China", url_name: "china", region_id: region2.id)
Country.create(name: "Indonesia", url_name: "indonesia", region_id: region2.id)
Country.create(name: "Mongolia", url_name: "mongolia", region_id: region2.id)
Country.create(name: "Myanmar (Burma)", url_name: "burma", region_id: region2.id)
Country.create(name: "Nepal", url_name: "nepal", region_id: region2.id)
Country.create(name: "Philippines", url_name: "philippines", region_id: region2.id)
Country.create(name: "Thailand", url_name: "thailand", region_id: region2.id)
Country.create(name: "Timor-Leste", url_name: "timor-leste", region_id: region2.id)

Country.create(name: "Dominican Republic", url_name: "dominican_republic", region_id: region3.id)
Country.create(name: "Eastern Caribbean", url_name: "eastern_caribbean", region_id: region3.id)
Country.create(name: "Jamaica", url_name: "jamaica", region_id: region3.id)

Country.create(name: "Belize", url_name: "belize", region_id: region4.id)
Country.create(name: "Costa Rica", url_name: "costa_rica", region_id: region4.id)
Country.create(name: "El Salvador", url_name: "el_salvador", region_id: region4.id)
Country.create(name: "Guatemala", url_name: "guatemala", region_id: region4.id)
Country.create(name: "Mexico", url_name: "mexico", region_id: region4.id)
Country.create(name: "Nicaragua", url_name: "nicaragua", region_id: region4.id)
Country.create(name: "Panama", url_name: "panama", region_id: region4.id)

Country.create(name: "Albania", url_name: "albania", region_id: region5.id)
Country.create(name: "Armenia", url_name: "armenia", region_id: region5.id)
Country.create(name: "Azerbaijan", url_name: "azerbaijan", region_id: region5.id)
Country.create(name: "Georgia", url_name: "georgia", region_id: region5.id)
Country.create(name: "Kosovo", url_name: "kosovo", region_id: region5.id)
Country.create(name: "Kyrgyz Republic", url_name: "kyrgyz_republic", region_id: region5.id)
Country.create(name: "Macedonia", url_name: "macedonia", region_id: region5.id)
Country.create(name: "Moldova", url_name: "moldova", region_id: region5.id)
Country.create(name: "Ukraine", url_name: "ukraine", region_id: region5.id)

Country.create(name: "Jordan", url_name: "jordan", region_id: region6.id)
Country.create(name: "Morocco", url_name: "morocco", region_id: region6.id)
Country.create(name: "Tunisia", url_name: "tunisia", region_id: region6.id)

Country.create(name: "Fiji", url_name: "fiji", region_id: region7.id)
Country.create(name: "Micronesia", url_name: "micronesia", region_id: region7.id)
Country.create(name: "Palau", url_name: "palau", region_id: region7.id)
Country.create(name: "Samoa", url_name: "samoa", region_id: region7.id)
Country.create(name: "Tonga", url_name: "tonga", region_id: region7.id)
Country.create(name: "Vanautu", url_name: "vanuatu", region_id: region7.id)

Country.create(name: "Colombia", url_name: "colombia", region_id: region8.id)
Country.create(name: "Ecuador", url_name: "ecuador", region_id: region8.id)
Country.create(name: "Guyana", url_name: "guyana", region_id: region8.id)
Country.create(name: "Paraguay", url_name: "paraguay", region_id: region8.id)
Country.create(name: "Peru", url_name: "peru", region_id: region8.id)

