# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# region1 = Region.create(name: "Africa", url_name: "africa")
# region2 = Region.create(name: "Asia", url_name: "asia")
# region3 = Region.create(name: "Caribbean", url_name: "caribbean")
# region4 = Region.create(name: "Central America and Mexico", url_name: "central_america_mexico")
# region5 = Region.create(name: "Eastern Europe and Central Asia", url_name: "eastern_europe_central_asia")
# region6 = Region.create(name: "North Africa and the Middle East", url_name: "north_africa_middle_east")
# region7 = Region.create(name: "Pacific Islands", url_name: "pacific_islands")
# region8 = Region.create(name: "South America", url_name: "south_america")


# Country.create(name: "Benin", url_name: "benin", region_id: region1.id)
# Country.create(name: "Botswana", url_name: "botswana", region_id: region1.id)
# Country.create(name: "Burkina Faso", url_name: "burkina_faso", region_id: region1.id)
# Country.create(name: "Cameroon", url_name: "cameroon", region_id: region1.id)
# Country.create(name: "Comoros", url_name: "comoros", region_id: region1.id)
# Country.create(name: "Ethiopia", url_name: "ethiopia", region_id: region1.id)
# Country.create(name: "Ghana", url_name: "ghana", region_id: region1.id)
# Country.create(name: "Guinea", url_name: "guinea", region_id: region1.id)
# Country.create(name: "Kenya", url_name: "kenya", region_id: region1.id)
# Country.create(name: "Lesotho", url_name: "lesotho", region_id: region1.id)
# Country.create(name: "Liberia", url_name: "liberia", region_id: region1.id)
# Country.create(name: "Madagascar", url_name: "madagascar", region_id: region1.id)
# Country.create(name: "Malawi", url_name: "malawi", region_id: region1.id)
# Country.create(name: "Mali", url_name: "mali", region_id: region1.id)
# Country.create(name: "Mozambique", url_name: "mozambique", region_id: region1.id)
# Country.create(name: "Namibia", url_name: "namibia", region_id: region1.id)
# Country.create(name: "Niger", url_name: "niger", region_id: region1.id)
# Country.create(name: "Rwanda", url_name: "rwanda", region_id: region1.id)
# Country.create(name: "Senegal", url_name: "senegal", region_id: region1.id)
# Country.create(name: "Sierra Leone", url_name: "sierra_leone", region_id: region1.id)
# Country.create(name: "South Africa", url_name: "south_africa", region_id: region1.id)
# Country.create(name: "Swaziland", url_name: "swaziland", region_id: region1.id)
# Country.create(name: "Tanzania", url_name: "tanzania", region_id: region1.id)
# Country.create(name: "The Gambia", url_name: "the_gambia", region_id: region1.id)
# Country.create(name: "Togo", url_name: "togo", region_id: region1.id)
# Country.create(name: "Uganda", url_name: "uganda", region_id: region1.id)
# Country.create(name: "Zambia", url_name: "zambia", region_id: region1.id)

# Country.create(name: "Cambodia", url_name: "cambodia", region_id: region2.id)
# Country.create(name: "China", url_name: "china", region_id: region2.id)
# Country.create(name: "Indonesia", url_name: "indonesia", region_id: region2.id)
# Country.create(name: "Mongolia", url_name: "mongolia", region_id: region2.id)
# Country.create(name: "Myanmar (Burma)", url_name: "burma", region_id: region2.id)
# Country.create(name: "Nepal", url_name: "nepal", region_id: region2.id)
# Country.create(name: "Philippines", url_name: "philippines", region_id: region2.id)
# Country.create(name: "Thailand", url_name: "thailand", region_id: region2.id)
# Country.create(name: "Timor-Leste", url_name: "timor-leste", region_id: region2.id)

# Country.create(name: "Dominican Republic", url_name: "dominican_republic", region_id: region3.id)
# Country.create(name: "Eastern Caribbean", url_name: "eastern_caribbean", region_id: region3.id)
# Country.create(name: "Jamaica", url_name: "jamaica", region_id: region3.id)

# Country.create(name: "Belize", url_name: "belize", region_id: region4.id)
# Country.create(name: "Costa Rica", url_name: "costa_rica", region_id: region4.id)
# Country.create(name: "El Salvador", url_name: "el_salvador", region_id: region4.id)
# Country.create(name: "Guatemala", url_name: "guatemala", region_id: region4.id)
# Country.create(name: "Mexico", url_name: "mexico", region_id: region4.id)
# Country.create(name: "Nicaragua", url_name: "nicaragua", region_id: region4.id)
# Country.create(name: "Panama", url_name: "panama", region_id: region4.id)

# Country.create(name: "Albania", url_name: "albania", region_id: region5.id)
# Country.create(name: "Armenia", url_name: "armenia", region_id: region5.id)
# Country.create(name: "Azerbaijan", url_name: "azerbaijan", region_id: region5.id)
# Country.create(name: "Georgia", url_name: "georgia", region_id: region5.id)
# Country.create(name: "Kosovo", url_name: "kosovo", region_id: region5.id)
# Country.create(name: "Kyrgyz Republic", url_name: "kyrgyz_republic", region_id: region5.id)
# Country.create(name: "Macedonia", url_name: "macedonia", region_id: region5.id)
# Country.create(name: "Moldova", url_name: "moldova", region_id: region5.id)
# Country.create(name: "Ukraine", url_name: "ukraine", region_id: region5.id)

# Country.create(name: "Jordan", url_name: "jordan", region_id: region6.id)
# Country.create(name: "Morocco", url_name: "morocco", region_id: region6.id)
# Country.create(name: "Tunisia", url_name: "tunisia", region_id: region6.id)

# Country.create(name: "Fiji", url_name: "fiji", region_id: region7.id)
# Country.create(name: "Micronesia", url_name: "micronesia", region_id: region7.id)
# Country.create(name: "Palau", url_name: "palau", region_id: region7.id)
# Country.create(name: "Samoa", url_name: "samoa", region_id: region7.id)
# Country.create(name: "Tonga", url_name: "tonga", region_id: region7.id)
# Country.create(name: "Vanautu", url_name: "vanuatu", region_id: region7.id)

# Country.create(name: "Colombia", url_name: "colombia", region_id: region8.id)
# Country.create(name: "Ecuador", url_name: "ecuador", region_id: region8.id)
# Country.create(name: "Guyana", url_name: "guyana", region_id: region8.id)
# Country.create(name: "Paraguay", url_name: "paraguay", region_id: region8.id)
# Country.create(name: "Peru", url_name: "peru", region_id: region8.id)

Country.find(1).update(latitude: 6.4667, longitude: 2.6000)
Country.find(2).update(latitude: -24.6583, longitude: 25.9083)
Country.find(3).update(latitude: 12.3333, longitude: -1.6667 )
Country.find(4).update(latitude: 3.8667, longitude: 11.5167)
Country.find(5).update(latitude: -11.6833, longitude: 43.2667)
Country.find(6).update(latitude: 9.0167, longitude: 38.7500)
Country.find(7).update(latitude: 5.5500, longitude: -0.2000)
Country.find(8).update(latitude: 9.5167, longitude: -13.7000)
Country.find(9).update(latitude: -1.2667, longitude: 36.8000)
Country.find(10).update(latitude: -29.4667, longitude: 27.9333)
Country.find(11).update(latitude: 6.3167, longitude: -10.8000)
Country.find(12).update(latitude: -20.0000, longitude: 47.0000)
Country.find(13).update(latitude: -13.9500, longitude: 33.7000)
Country.find(14).update(latitude: 12.6500, longitude: -8.0000)
Country.find(15).update(latitude: -25.9500, longitude: 32.5833)
Country.find(16).update(latitude: -22.5700, longitude: 17.0861)
Country.find(17).update(latitude: 13.5333, longitude: 2.0833)
Country.find(18).update(latitude: -1.9403, longitude: 29.8739)
Country.find(19).update(latitude: 14.6667, longitude: -17.4167)
Country.find(20).update(latitude: 8.4844, longitude: -13.2344)
Country.find(21).update(latitude: -30.0000, longitude: 25.0000)
Country.find(22).update(latitude: -26.3167, longitude: 31.1333)
Country.find(23).update(latitude: -6.3070, longitude: 34.8540)
Country.find(24).update(latitude: 13.4667, longitude: -16.6000)
Country.find(25).update(latitude: 6.1167, longitude: 1.2167)
Country.find(26).update(latitude: 1.0667, longitude: 31.8833)
Country.find(27).update(latitude: -15.4167, longitude: 28.2833)

Country.find(28).update(latitude: 11.5500, longitude: 104.9167)
Country.find(29).update(latitude: 35.0000, longitude: 103.0000)
Country.find(30).update(latitude: -6.1750, longitude: 106.8283)
Country.find(31).update(latitude: 46.0000, longitude: 105.0000)
Country.find(32).update(latitude: 22.0000, longitude: 96.0000)
Country.find(33).update(latitude: 26.5333, longitude: 86.7333)
Country.find(34).update(latitude: 13.0000, longitude: 122.0000)
Country.find(35).update(latitude: 13.7500, longitude: 100.4833)
Country.find(36).update(latitude: -8.5667, longitude: 125.5667)

Country.find(37).update(latitude: 19.0000, longitude: -70.6667)
Country.find(38).update(latitude: 14.0167, longitude: -60.9833)
Country.find(39).update(latitude: 18.1824, longitude: -77.3218)

Country.find(40).update(latitude: 17.2500, longitude: -88.7667)
Country.find(41).update(latitude: 9.9333, longitude: -84.0833)
Country.find(42).update(latitude: 13.6667, longitude: -89.1667)
Country.find(43).update(latitude: 14.6133, longitude: -90.5353)
Country.find(44).update(latitude: 19.0000, longitude: -99.1333)
Country.find(45).update(latitude: 13.0000, longitude: -86.0000)
Country.find(46).update(latitude: 8.9833, longitude: -79.5167)

Country.find(47).update(latitude: 41.0000, longitude: 20.0000)
Country.find(48).update(latitude: 40.1833, longitude: 44.5167)
Country.find(49).update(latitude: 40.3000, longitude: 47.7000)
Country.find(50).update(latitude: 41.7167, longitude: 44.7833)
Country.find(51).update(latitude: 42.6000, longitude: 20.8500)
Country.find(52).update(latitude: 42.8667, longitude: 74.6000)
Country.find(53).update(latitude: 41.6000, longitude: 21.7000)
Country.find(54).update(latitude: 47.0000, longitude: 28.9167)
Country.find(55).update(latitude: 49.0000, longitude: 32.0000)

Country.find(56).update(latitude: 31.9500, longitude: 35.9333)
Country.find(57).update(latitude: 32.0000, longitude: -6.0000)
Country.find(58).update(latitude: 34.0000, longitude: 9.0000)

Country.find(59).update(latitude: -18.0000, longitude: 179.0000)
Country.find(60).update(latitude: 6.9167, longitude: 158.1833)
Country.find(61).update(latitude: 7.5000, longitude: 134.6167)
Country.find(62).update(latitude: -13.8333, longitude: -171.7500)
Country.find(63).update(latitude: -21.1333, longitude: -175.2000)
Country.find(64).update(latitude: -17.7500, longitude: 168.3000)

Country.find(65).update(latitude: 4.5833, longitude: -74.0667)
Country.find(66).update(latitude: -0.1500, longitude: -78.3500)
Country.find(67).update(latitude: 5.0000, longitude: -58.7500)
Country.find(68).update(latitude: -25.2667, longitude: -57.6667)
Country.find(69).update(latitude: -12.0433, longitude: -77.0283)


